export const PATHS = {
  LOGIN: "/login",
  DASHBOARD: "/",
  MANGAS: "/manga",
  EDIT_MANGA: (mangaId: string) => "/manga/edit/" + mangaId,
  CHAPTERS_MANGA: (mangaId: string) => "/manga/chapters/list/" + mangaId,
  ADD_CHAPTER_MANGA: (mangaId: string) => "/manga/chapters/add/" + mangaId,
  EDIT_CHAPTER_MANGA: (chapterId: string) =>
    "/manga/chapters/edit/" + chapterId,
  NOVELS: "/novels",
  GENRES: "/genres",
  CATEGORIES: "/categories",
  COMMENTS: "/comments",
  USERS: "/users",
  NOTIFICATIONS: "/notifications",
  BANNERS: "/banners",
  AVATARS: "/avatars",
  CONTENT_REQUESTS: "/content-requests",
  CHAPTER_REQUESTS: "/chapter-requests",
  SUB_PLANS: "/subscription-plans",
  EMPLOYEES: "/employees",
  PAYMENTS: "/payments",
  ADMIN_LOGS: "/admin-logs",
};
