/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface EntityToolExportResponse {
  draft_id?: string;
  duplicate?: boolean;
  export_version?: number;
  pages_count?: number;
  project_id?: string;
  status?: string;
}
