/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface EntityMangaInfoSimple {
  image_url?: string;
  is_bookmarked?: boolean;
  manga_id?: string;
  slug?: string;
  title?: string;
  type?: string;
}
