/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface EntityToolLinkInfo {
  external_user_id?: number;
  first_name?: string;
  last_name?: string;
  link_id?: string;
  linked_at?: string;
  mano_user_id?: string;
  picture_link?: string;
  role?: string;
  tool_user_id?: string;
  tool_username?: string;
  username?: string;
}
