/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface EntityAdminLogItem {
  action?: string;
  admin_first_name?: string;
  admin_id?: string;
  admin_last_name?: string;
  admin_username?: string;
  created_at?: string;
  description?: string;
  entity_id?: string;
  entity_type?: string;
  id?: string;
  meta?: unknown;
}
