/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface EntityToolLinkRevokeRequest {
  mano_user_id?: string;
  reason?: string;
  tool_user_id?: string;
}
