/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { EntityMangaResponse } from './entityMangaResponse';

export interface EntityBookmarkResponse {
  bookmark_id?: string;
  created_at?: string;
  manga?: EntityMangaResponse;
  manga_id?: string;
  updated_at?: string;
  user_id?: string;
}
