/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { EntityParserSiteInfo } from './entityParserSiteInfo';

export interface EntityParserSitesResponse {
  enabled?: boolean;
  sites?: EntityParserSiteInfo[];
}
