/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { EntityCategoryInfo } from './entityCategoryInfo';
import type { EntityChapterResponseSimple } from './entityChapterResponseSimple';
import type { EntityGenreInfo } from './entityGenreInfo';
import type { EntityTranslatorInfo } from './entityTranslatorInfo';

export interface EntityMangaResponse {
  age_restriction?: string;
  author?: string;
  average_rating?: number;
  bookmarked_count?: number;
  categories?: EntityCategoryInfo[];
  chapters?: EntityChapterResponseSimple[];
  chapters_count?: number;
  created_at?: string;
  description?: string;
  genres?: EntityGenreInfo[];
  image_url?: string;
  is_bookmarked?: boolean;
  is_comment_enabled?: boolean;
  is_showed?: boolean;
  likes_count?: number;
  manga_id?: string;
  real_link?: string;
  release_status?: string;
  release_year?: number;
  second_title?: string;
  showing_date?: string;
  slug?: string;
  title?: string;
  translation_status?: string;
  translators?: EntityTranslatorInfo[];
  type?: string;
  updated_at?: string;
  views_count?: number;
}
