/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { EntityParserJob } from './entityParserJob';

export interface EntityParserJobListResponse {
  jobs?: EntityParserJob[];
  limit?: number;
}
