/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { MangaparserDroppedPage } from './mangaparserDroppedPage';
import type { MangaparserFailedPage } from './mangaparserFailedPage';
import type { MangaparserLayoutResult } from './mangaparserLayoutResult';
import type { MangaparserPageInfo } from './mangaparserPageInfo';

export interface EntityParserChapterResult {
  download_duration_ms?: number;
  dropped?: MangaparserDroppedPage[];
  extension_mismatches?: number;
  failed?: MangaparserFailedPage[];
  image_urls?: number;
  layout?: MangaparserLayoutResult;
  pages?: MangaparserPageInfo[];
  pages_count?: number;
  slug?: string;
  total_image_bytes?: number;
  warnings?: string[];
  zip_bytes?: number;
  zip_object_key?: string;
  zip_url?: string;
}
