/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface EntityParserSiteStats {
  fail_count?: number;
  last_error_code?: string;
  last_error_message?: string;
  last_fail_at?: string;
  last_ok_at?: string;
  ok_count?: number;
}
