/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { EntityParserChapterResult } from './entityParserChapterResult';
import type { EntityParserJobError } from './entityParserJobError';
import type { EntityParserJobProgress } from './entityParserJobProgress';

export interface EntityParserJob {
  attempt?: number;
  chapters?: string[];
  child_job_ids?: string[];
  created_at?: string;
  created_by?: string;
  duration_ms?: number;
  error?: EntityParserJobError;
  finished_at?: string;
  id?: string;
  kind?: string;
  max_attempts?: number;
  max_chapters?: number;
  parent_job_id?: string;
  progress?: EntityParserJobProgress;
  result?: EntityParserChapterResult;
  site?: string;
  started_at?: string;
  status?: string;
  url?: string;
  warnings?: string[];
}
