/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { EntityToolLinkInfo } from './entityToolLinkInfo';

export interface EntityToolLinkStartResponse {
  attempts_left?: number;
  channels?: string[];
  expires_in?: number;
  link?: EntityToolLinkInfo;
  masked_name?: string;
  status?: string;
}
