/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { EntityChapterInfoSimple } from './entityChapterInfoSimple';
import type { EntityMangaInfoSimple } from './entityMangaInfoSimple';

export interface EntityReadingHistoryItem {
  chapter?: EntityChapterInfoSimple;
  current_chapter?: number;
  current_chapter_rank?: number;
  last_chapter_number?: number;
  last_page_id?: string;
  last_page_number?: number;
  last_read_at?: string;
  manga?: EntityMangaInfoSimple;
  progress_id?: string;
  progress_percentage?: number;
  total_chapters?: number;
  total_chapters_in_manga?: number;
}
