/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface EntityToolLinkConfirmRequest {
  code?: string;
  external_user_id?: number;
  tool_user_id?: string;
  tool_username?: string;
}
