/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface EntityCreateParserJobRequest {
  kind?: string;
  max_chapters?: number;
  /** @maxLength 2048 */
  url: string;
}
