/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { EntityToolLinkInfo } from './entityToolLinkInfo';

export interface EntityToolLinkStatusResponse {
  link?: EntityToolLinkInfo;
  linked?: boolean;
}
