/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { EntityParserSiteStats } from './entityParserSiteStats';
import type { MangaparserLayout } from './mangaparserLayout';

export interface EntityParserSiteInfo {
  host?: string;
  layout_hint?: MangaparserLayout;
  markers?: string[];
  name?: string;
  stats?: EntityParserSiteStats;
}
