/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface EntityChapterInfoSimple {
  chapter_id?: string;
  chapter_number?: number;
  chapter_title?: string;
  total_pages?: number;
}
