/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type GetAdminTransactionsCountParams = {
/**
 * Filter by user ID
 */
user_id?: string;
/**
 * Filter by transaction type
 */
transaction_type?: string;
/**
 * Filter by status
 */
status?: string;
/**
 * Filter by payment method
 */
payment_method?: string;
/**
 * Filter by manga ID
 */
manga_id?: string;
/**
 * Filter by chapter ID
 */
chapter_id?: string;
/**
 * Filter by purchase type
 */
purchase_type?: string;
/**
 * Filter by date from (RFC3339)
 */
date_from?: string;
/**
 * Filter by date to (RFC3339)
 */
date_to?: string;
/**
 * Search in reason/description
 */
search?: string;
};
