/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type GetAdminCompanyDonationsParams = {
/**
 * Filter by manga ID
 */
manga_id?: string;
/**
 * Filter by chapter ID
 */
chapter_id?: string;
/**
 * Filter by user ID who donated
 */
from_user_id?: string;
/**
 * Filter by date from (RFC3339)
 */
date_from?: string;
/**
 * Filter by date to (RFC3339)
 */
date_to?: string;
/**
 * Limit (default 20)
 */
limit?: number;
};
