/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type GetAdminTransactionsListParams = {
/**
 * Filter by user ID
 */
user_id?: string;
/**
 * Filter by transaction type
 */
transaction_type?: string;
/**
 * Filter by status
 */
status?: string;
/**
 * Filter by payment method
 */
payment_method?: string;
/**
 * Filter by manga ID
 */
manga_id?: string;
/**
 * Filter by chapter ID
 */
chapter_id?: string;
/**
 * Filter by purchase type
 */
purchase_type?: string;
/**
 * Filter by date from (RFC3339)
 */
date_from?: string;
/**
 * Filter by date to (RFC3339)
 */
date_to?: string;
/**
 * Search in reason/description
 */
search?: string;
/**
 * Cursor for pagination (created_at)
 */
cursor_created_at?: string;
/**
 * Cursor for pagination (transaction_id)
 */
cursor_id?: string;
/**
 * Limit (default 20, max 100)
 */
limit?: number;
};
