/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type GetAdminAnalyticsTopTagsParams = {
/**
 * Limit (default 10, max 100)
 */
limit?: number;
};
