/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type GetAdminLogsParams = {
/**
 * Items per page (default 20, max 100)
 */
limit?: number;
/**
 * Cursor: created_at of last item (RFC3339)
 */
cursor_created_at?: string;
/**
 * Cursor: id of last item (UUID)
 */
cursor_id?: string;
/**
 * Filter by admin UUID
 */
admin_id?: string;
/**
 * Filter by entity type (chapter, user, manga)
 */
entity_type?: string;
/**
 * Filter by entity UUID
 */
entity_id?: string;
/**
 * Filter by action (e.g. chapter.set_translator)
 */
action?: string;
};
