/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type GetAdminAnalyticsTranslatorsIdChaptersStatsParams = {
/**
 * Limit (default 20, max 100)
 */
limit?: number;
/**
 * Offset (default 0)
 */
offset?: number;
};
