/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type GetAdminAnalyticsActivityHistoryParams = {
/**
 * Number of months (default 7, max 24)
 */
months?: number;
};
