/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type GetAdminTranslatorTransactionsParams = {
/**
 * Filter by translator ID
 */
translator_id?: string;
/**
 * Filter by status (completed, pending)
 */
status?: string;
/**
 * Filter from date (RFC3339)
 */
date_from?: string;
/**
 * Filter to date (RFC3339)
 */
date_to?: string;
/**
 * Cursor created_at (RFC3339)
 */
cursor_created_at?: string;
/**
 * Cursor transaction_id
 */
cursor_id?: string;
/**
 * Limit (default 20, max 100)
 */
limit?: number;
};
