/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type GetAvatarsParams = {
/**
 * Page number
 */
page?: number;
/**
 * Limit per page
 */
limit?: number;
};
