/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type GetAdminAnalyticsTranslatorsIdContentsParams = {
/**
 * manga_type filter (manga, manhwa, manhua, novella, comics, author_works)
 */
type?: string;
};
