/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type GetBookmarksParams = {
/**
 * Limit
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Offset
 * @minimum 0
 */
offset?: number;
};
