/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { GetContentTrendTypes } from './getContentTrendTypes';

export type GetContentTrendParams = {
/**
 * Page number
 */
page?: number;
/**
 * Items per page
 */
limit?: number;
/**
 * Filter by types (comma-separated)
 */
types?: GetContentTrendTypes;
/**
 * Filter by genre IDs (comma-separated UUIDs)
 */
genre_ids?: string;
/**
 * Filter by category IDs (comma-separated UUIDs)
 */
category_ids?: string;
};
