/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type GetCommentsMangaMangaIdParams = {
/**
 * Include replies
 */
include_replies?: boolean;
/**
 * Only pinned comments
 */
only_pinned?: boolean;
/**
 * Sort by most liked (pinned first, then by likes desc)
 */
most_interested?: boolean;
/**
 * Limit
 */
limit?: number;
/**
 * Offset
 */
offset?: number;
};
