/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type GetCommentsParams = {
/**
 * Manga ID filter
 */
manga_id?: string;
/**
 * Chapter ID filter
 */
chapter_id?: string;
/**
 * Search text (comment text, user name, manga/chapter title)
 */
search?: string;
/**
 * Include replies
 */
include_replies?: boolean;
/**
 * Only pinned comments
 */
only_pinned?: boolean;
/**
 * Limit
 */
limit?: number;
/**
 * Offset
 */
offset?: number;
};
