/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type GetCommentsCountParams = {
/**
 * Manga ID
 */
manga_id?: string;
/**
 * Chapter ID
 */
chapter_id?: string;
};
