/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type GetContentDraftsParams = {
/**
 * Filter by status (pending_review, approved, rejected)
 */
status?: string;
/**
 * Filter by content type
 */
type?: string;
/**
 * Limit
 */
limit?: number;
/**
 * Offset
 */
offset?: number;
};
