/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type GetContentDraftsMineParams = {
/**
 * Limit
 */
limit?: number;
/**
 * Offset
 */
offset?: number;
};
