/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type GetDraftParams = {
/**
 * Filter by status (draft, pending_review, approved, rejected)
 */
status?: string;
/**
 * Filter by manga UUID
 */
manga_id?: string;
/**
 * Filter by draft type (novella, manga)
 */
type?: string;
/**
 * Limit
 */
limit?: number;
/**
 * Offset
 */
offset?: number;
};
