/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type GetHomeCategoriesParams = {
/**
 * Page
 */
page?: number;
/**
 * Limit
 */
limit?: number;
};
