/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type GetMangaMangaIdChaptersParams = {
/**
 * Items per page
 */
limit?: number;
/**
 * Offset
 */
offset?: number;
/**
 * Search by chapter title or chapter number
 */
search?: string;
/**
 * Order direction: asc, desc
 */
order_dir?: string;
};
