/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type GetMangaType = typeof GetMangaType[keyof typeof GetMangaType];


export const GetMangaType = {
  manga: 'manga',
  manhwa: 'manhwa',
  manhua: 'manhua',
  novella: 'novella',
  comics: 'comics',
  author_works: 'author_works',
} as const;
