/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { GetMangaSortBy } from './getMangaSortBy';
import type { GetMangaType } from './getMangaType';
import type { GetMangaTypes } from './getMangaTypes';

export type GetMangaParams = {
/**
 * Page number
 */
page?: number;
/**
 * Items per page
 */
limit?: number;
/**
 * Search by title, author, description
 */
search?: string;
/**
 * Filter by type
 */
type?: GetMangaType;
/**
 * Filter by content types (comma-separated)
 */
types?: GetMangaTypes;
/**
 * Filter by release statuses (comma-separated)
 */
release_statuses?: string;
/**
 * Filter by translation statuses (comma-separated)
 */
translation_statuses?: string;
/**
 * Filter by age restrictions (comma-separated)
 */
age_restrictions?: string;
/**
 * Filter by genre IDs (comma-separated)
 */
genre_ids?: string;
/**
 * Filter by category IDs (comma-separated)
 */
category_ids?: string;
/**
 * Sort by
 */
sort_by?: GetMangaSortBy;
};
