/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type GetNotificationParams = {
/**
 * Page
 */
page?: number;
/**
 * Limit
 */
limit?: number;
/**
 * Status (read/unread)
 */
status?: string;
/**
 * Platform (telegram/push/email)
 */
platform?: string;
/**
 * Is Read (true=read, false=unread)
 */
is_read?: boolean;
};
