/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type GetNovelsSortBy = typeof GetNovelsSortBy[keyof typeof GetNovelsSortBy];


export const GetNovelsSortBy = {
  most_liked: 'most_liked',
  most_viewed: 'most_viewed',
  highest_rated: 'highest_rated',
  newest: 'newest',
  latest_chapter: 'latest_chapter',
} as const;
