/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { GetNovelsSortBy } from './getNovelsSortBy';

export type GetNovelsParams = {
/**
 * Page
 */
page?: number;
/**
 * Limit
 */
limit?: number;
/**
 * Search by title, author, description
 */
search?: string;
/**
 * Filter by release statuses (comma-separated)
 */
release_statuses?: string;
/**
 * Filter by age restrictions (comma-separated)
 */
age_restrictions?: string;
/**
 * Filter by genre IDs (comma-separated)
 */
genre_ids?: string;
/**
 * Sort by
 */
sort_by?: GetNovelsSortBy;
};
