/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { GetNovelsNovelIdChaptersOrderDir } from './getNovelsNovelIdChaptersOrderDir';

export type GetNovelsNovelIdChaptersParams = {
/**
 * Page
 */
page?: number;
/**
 * Limit
 */
limit?: number;
/**
 * Search by title or chapter number
 */
search?: string;
/**
 * Order direction
 */
order_dir?: GetNovelsNovelIdChaptersOrderDir;
};
