/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type GetPaymentTransactionsParams = {
/**
 * Cursor for pagination
 */
cursor?: string;
/**
 * Page size (default 20, max 100)
 */
page_size?: number;
};
