/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type GetReadingProgressParams = {
/**
 * Limit
 * @minimum 1
 * @maximum 50
 */
limit?: number;
/**
 * Offset
 * @minimum 0
 */
offset?: number;
/**
 * Only manga whose current read chapter is not the latest visible chapter
 */
unfinished?: boolean;
};
