/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type GetReportsParams = {
/**
 * Filter by user ID
 */
user_id?: string;
/**
 * Filter by manga ID
 */
manga_id?: string;
/**
 * Filter by chapter ID
 */
chapter_id?: string;
/**
 * Filter by status (pending, reviewed, resolved, rejected)
 */
status?: string;
/**
 * Filter by type (suggestions, feedback, complaints, invalid_grammar, technical_issue, other_issue, duplicate_image)
 */
report_type?: string;
/**
 * Limit (default 20)
 */
limit?: number;
/**
 * Offset (default 0)
 */
offset?: number;
};
