/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type GetUserCountParams = {
/**
 * Search by name, username, or phone number
 */
search?: string;
/**
 * Filter by roles (comma-separated e.g., admin,translator OR multiple params e.g., roles=admin&roles=translator). Available: admin, translator, user, moderator, superadmin
 */
roles?: string;
};
