/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface MangaparserDroppedPage {
  bytes?: number;
  height?: number;
  index?: number;
  reason?: string;
  source_url?: string;
  width?: number;
}
