/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type MangaparserLayout = typeof MangaparserLayout[keyof typeof MangaparserLayout];


export const MangaparserLayout = {
  LayoutUnknown: 'unknown',
  LayoutManga: 'manga',
  LayoutManhwa: 'manhwa',
} as const;
