/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { MangaparserLayout } from './mangaparserLayout';
import type { MangaparserLayoutSignals } from './mangaparserLayoutSignals';

export interface MangaparserLayoutResult {
  /** 0..1 */
  confidence?: number;
  reason?: string;
  signals?: MangaparserLayoutSignals;
  type?: MangaparserLayout;
}
