/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { MangaparserCode } from './mangaparserCode';

export interface MangaparserFailedPage {
  code?: MangaparserCode;
  index?: number;
  message?: string;
  source_url?: string;
  /** upstream HTTP status, when the CDN answered */
  status?: number;
}
