/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { MangaparserLayout } from './mangaparserLayout';

export interface MangaparserLayoutSignals {
  dominant_height?: number;
  /** most common width */
  dominant_width?: number;
  /** median height/width */
  median_aspect?: number;
  p10_aspect?: number;
  p90_aspect?: number;
  pages?: number;
  /** SeamMatches / SeamPairs */
  seam_continuity?: number;
  /** pairs whose bottom/top rows continue each other */
  seam_matches?: number;
  /** adjacent pairs with textured edges that were compared */
  seam_pairs?: number;
  site_hint?: MangaparserLayout;
  /** share of pages with aspect >= 2.0 */
  tall_pages_share?: number;
  uniform_height_share?: number;
  /** share of pages with the dominant width */
  uniform_width_share?: number;
}
