/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type MangaparserCode = typeof MangaparserCode[keyof typeof MangaparserCode];


export const MangaparserCode = {
  CodeInvalidURL: 'invalid_url',
  CodeUnsupportedSite: 'unsupported_site',
  CodeBlockedHost: 'blocked_host',
  CodeSiteStructureChanged: 'site_structure_changed',
  CodeChallengeFailed: 'challenge_failed',
  CodeRateLimited: 'rate_limited',
  CodeUpstreamHTTP: 'upstream_http_error',
  CodeNetwork: 'network_error',
  CodeTimeout: 'timeout',
  CodeCanceled: 'canceled',
  CodeNoImages: 'no_images',
  CodeDownloadFailed: 'download_failed',
  CodeTooManyPages: 'too_many_pages',
  CodeTooLarge: 'too_large',
  CodeUnexpectedContent: 'unexpected_content',
  CodeStorage: 'storage_error',
  CodeInternal: 'internal_error',
} as const;
