/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface MangaparserPageInfo {
  bytes?: number;
  content_type?: string;
  /** full decode succeeded (integrity) */
  decoded?: boolean;
  filename?: string;
  /** detected from bytes */
  format?: string;
  height?: number;
  /** 1-based source position; file names keep gaps for failed/dropped pages */
  index?: number;
  source_url?: string;
  url_extension?: string;
  width?: number;
}
