/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type PostUploadZipBody = {
  /** ZIP file with images (jpg, png, webp, gif) */
  file: Blob | File;
};
