/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

/**
 * Content type
 */
export type PostContentDraftsBodyType = typeof PostContentDraftsBodyType[keyof typeof PostContentDraftsBodyType];


export const PostContentDraftsBodyType = {
  manga: 'manga',
  manhwa: 'manhwa',
  manhua: 'manhua',
  novella: 'novella',
  comics: 'comics',
  author_works: 'author_works',
} as const;
