/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { PostContentDraftsBodyType } from './postContentDraftsBodyType';

export type PostContentDraftsBody = {
  /** Cover image (jpg, jpeg, png, webp, gif) */
  cover?: Blob | File;
  /** Content type */
  type: PostContentDraftsBodyType;
  /** Title */
  title: string;
  /** Slug */
  slug?: string;
  /** Second title */
  second_title?: string;
  /** Description */
  description?: string;
  /** Author */
  author?: string;
  /** Real link */
  real_link?: string;
  /** Release status */
  release_status: string;
  /** Translation status */
  translation_status: string;
  /** Age restriction */
  age_restriction: string;
  /** Release year */
  release_year?: number;
  /** Is comment enabled */
  is_comment_enabled?: boolean;
  /** Showing date (RFC3339) */
  showing_date?: string;
  /** Comma-separated genre UUIDs */
  genre_ids?: string;
  /** Comma-separated category UUIDs */
  category_ids?: string;
  /** Comma-separated tag UUIDs */
  tag_ids?: string;
  /** Comma-separated translator UUIDs */
  translator_ids?: string;
  /** Message to moderator */
  message_to_moderator: string;
};
