/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface RequestUpdateCommentRequest {
  /**
     * @minLength 1
     * @maxLength 5000
     */
  text: string;
}
