/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface RequestRateMangaRequest {
  /**
     * @minimum 1
     * @maximum 10
     */
  rating: number;
}
