/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface RequestCreateCommentRequest {
  chapter_id?: string;
  manga_id: string;
  parent_comment_id?: string;
  replies_to_user_id?: string;
  /**
     * @minLength 1
     * @maxLength 5000
     */
  text: string;
}
