/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type RequestUpsertHomeCategoryRequestTimePeriod = typeof RequestUpsertHomeCategoryRequestTimePeriod[keyof typeof RequestUpsertHomeCategoryRequestTimePeriod];


export const RequestUpsertHomeCategoryRequestTimePeriod = {
  all: 'all',
  day: 'day',
  week: 'week',
  month: 'month',
} as const;
