/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { RequestUpdateMangaRequestAgeRestriction } from './requestUpdateMangaRequestAgeRestriction';
import type { RequestUpdateMangaRequestReleaseStatus } from './requestUpdateMangaRequestReleaseStatus';
import type { RequestUpdateMangaRequestTranslationStatus } from './requestUpdateMangaRequestTranslationStatus';
import type { RequestUpdateMangaRequestType } from './requestUpdateMangaRequestType';

export interface RequestUpdateMangaRequest {
  age_restriction?: RequestUpdateMangaRequestAgeRestriction;
  author?: string;
  category_ids?: string[];
  description?: string;
  genre_ids?: string[];
  image_url?: string;
  is_comment_enabled?: boolean;
  /** IsShowed publishes (true) or hides (false) the title for the public site. */
  is_showed?: boolean;
  real_link?: string;
  release_status?: RequestUpdateMangaRequestReleaseStatus;
  /**
     * @minimum 1900
     * @maximum 2100
     */
  release_year?: number;
  second_title?: string;
  showing_date?: string;
  /**
     * @minLength 1
     * @maxLength 255
     */
  slug?: string;
  tag_ids?: string[];
  /**
     * @minLength 1
     * @maxLength 500
     */
  title?: string;
  translation_status?: RequestUpdateMangaRequestTranslationStatus;
  translator_ids?: string[];
  type?: RequestUpdateMangaRequestType;
}
