/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { RequestUserTopupRequestProvider } from './requestUserTopupRequestProvider';

export interface RequestUserTopupRequest {
  /** @minimum 1 */
  amount?: number;
  plan_id?: string;
  provider: RequestUserTopupRequestProvider;
  return_url?: string;
}
