/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type RequestUpdateMangaRequestType = typeof RequestUpdateMangaRequestType[keyof typeof RequestUpdateMangaRequestType];


export const RequestUpdateMangaRequestType = {
  manga: 'manga',
  manhwa: 'manhwa',
  manhua: 'manhua',
  novella: 'novella',
  comics: 'comics',
  author_works: 'author_works',
} as const;
