/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface RequestUpsertBannerRequest {
  description: string;
  id: string;
  image_link: string;
  is_new_url?: boolean;
}
