/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { RequestPage } from './requestPage';

export interface RequestUpdateChapterRequest {
  /**
     * @minimum 0
     * @maximum 500
     */
  chapter_number?: number;
  is_free?: boolean;
  /** @minItems 1 */
  pages: RequestPage[];
  release_date: string;
  showing_date?: string;
  title?: string;
}
