/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type RequestUpdateNovelRequestReleaseStatus = typeof RequestUpdateNovelRequestReleaseStatus[keyof typeof RequestUpdateNovelRequestReleaseStatus];


export const RequestUpdateNovelRequestReleaseStatus = {
  finished: 'finished',
  freezed: 'freezed',
  'no-translator': 'no-translator',
  continue: 'continue',
  ongoing: 'ongoing',
} as const;
