/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface RequestCreateNovelChapterRequest {
  /** @minimum 0 */
  chapter_number?: number;
  content: string;
  is_free?: boolean;
  novel_id: string;
  release_date?: string;
  send_notification?: boolean;
  showing_date?: string;
  title?: string;
  translator_id?: string;
}
