/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface RequestUpdateNovelChapterRequest {
  /** @minimum 0 */
  chapter_number?: number;
  content?: string;
  is_free?: boolean;
  is_showed?: boolean;
  release_date?: string;
  showing_date?: string;
  title?: string;
}
