/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface RequestUpsertReadingProgressRequest {
  chapter_id: string;
  manga_id: string;
  page_id?: string;
  /** @minimum 1 */
  page_number: number;
}
