/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type RequestUpsertHomeCategoryRequestSortBy = typeof RequestUpsertHomeCategoryRequestSortBy[keyof typeof RequestUpsertHomeCategoryRequestSortBy];


export const RequestUpsertHomeCategoryRequestSortBy = {
  views: 'views',
  likes: 'likes',
} as const;
