/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface RequestUpsertGenreRequest {
  /** @maxLength 500 */
  description?: string;
  id?: string;
  /**
     * @minLength 3
     * @maxLength 100
     */
  name: string;
}
