/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type RequestCreateMangaRequestTranslationStatus = typeof RequestCreateMangaRequestTranslationStatus[keyof typeof RequestCreateMangaRequestTranslationStatus];


export const RequestCreateMangaRequestTranslationStatus = {
  finished: 'finished',
  freezed: 'freezed',
  'no-translator': 'no-translator',
  continue: 'continue',
} as const;
