/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface RequestApproveDraftRequest {
  /**
     * For drafts exported from the editing tool: the export version the
     * reviewer looked at. A newer export answers 409 export_version_conflict.
     */
  expected_export_version?: number;
  is_free?: boolean;
  release_date?: string;
  send_notification?: boolean;
  showing_date?: string;
}
