/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface RequestUpsertSubscriptionPlanRequest {
  description?: string;
  duration_days: number;
  is_active?: boolean;
  name: string;
  price: number;
}
