/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { RequestRejectMark } from './requestRejectMark';

export interface RequestRejectDraftRequest {
  expected_export_version?: number;
  marks?: RequestRejectMark[];
  overall_comment?: string;
  reject_reason?: string;
}
