/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface RequestCreateReportRequest {
  chapter_id?: string;
  comment_id?: string;
  manga_id?: string;
  /**
     * @minLength 1
     * @maxLength 2000
     */
  message: string;
  report_type: string;
}
