/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type RequestUserTopupRequestProvider = typeof RequestUserTopupRequestProvider[keyof typeof RequestUserTopupRequestProvider];


export const RequestUserTopupRequestProvider = {
  payme: 'payme',
  click: 'click',
} as const;
