/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { RequestMarkBBox } from './requestMarkBBox';

export interface RequestRejectMark {
  bbox?: RequestMarkBBox;
  comment?: string;
  id?: string;
  page_index?: number;
}
