/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type RequestUpdateMangaRequestTranslationStatus = typeof RequestUpdateMangaRequestTranslationStatus[keyof typeof RequestUpdateMangaRequestTranslationStatus];


export const RequestUpdateMangaRequestTranslationStatus = {
  finished: 'finished',
  freezed: 'freezed',
  'no-translator': 'no-translator',
  continue: 'continue',
} as const;
