/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type RequestUpdateNovelRequestAgeRestriction = typeof RequestUpdateNovelRequestAgeRestriction[keyof typeof RequestUpdateNovelRequestAgeRestriction];


export const RequestUpdateNovelRequestAgeRestriction = {
  all: 'all',
  '12+': '12+',
  '16+': '16+',
  '18+': '18+',
} as const;
