/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { RequestBulkCreateNotificationsRequestPlatform } from './requestBulkCreateNotificationsRequestPlatform';

export interface RequestBulkCreateNotificationsRequest {
  button_text?: string;
  button_url?: string;
  content: string;
  photo_url?: string;
  platform?: RequestBulkCreateNotificationsRequestPlatform;
  related_id?: string;
  status: string;
  title: string;
  type: string;
  /** @minItems 1 */
  user_ids: string[];
  webapp_button_text?: string;
  webapp_button_url?: string;
}
