/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type RequestCreateNovelRequestTranslationStatus = typeof RequestCreateNovelRequestTranslationStatus[keyof typeof RequestCreateNovelRequestTranslationStatus];


export const RequestCreateNovelRequestTranslationStatus = {
  finished: 'finished',
  freezed: 'freezed',
  'no-translator': 'no-translator',
  continue: 'continue',
} as const;
