/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { RequestUpsertHomeCategoryRequestSortBy } from './requestUpsertHomeCategoryRequestSortBy';
import type { RequestUpsertHomeCategoryRequestTimePeriod } from './requestUpsertHomeCategoryRequestTimePeriod';

export interface RequestUpsertHomeCategoryRequest {
  content_types?: string[];
  genre_ids?: string[];
  is_active?: boolean;
  /**
     * @minimum 1
     * @maximum 50
     */
  limit: number;
  /** @minimum 0 */
  order_index?: number;
  sort_by: RequestUpsertHomeCategoryRequestSortBy;
  time_period: RequestUpsertHomeCategoryRequestTimePeriod;
  /**
     * @minLength 1
     * @maxLength 200
     */
  title: string;
}
