/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { RequestCreateMangaRequestAgeRestriction } from './requestCreateMangaRequestAgeRestriction';
import type { RequestCreateMangaRequestReleaseStatus } from './requestCreateMangaRequestReleaseStatus';
import type { RequestCreateMangaRequestTranslationStatus } from './requestCreateMangaRequestTranslationStatus';
import type { RequestCreateMangaRequestType } from './requestCreateMangaRequestType';

export interface RequestCreateMangaRequest {
  age_restriction: RequestCreateMangaRequestAgeRestriction;
  author?: string;
  category_ids?: string[];
  description?: string;
  genre_ids?: string[];
  image_url?: string;
  is_comment_enabled?: boolean;
  real_link?: string;
  release_status: RequestCreateMangaRequestReleaseStatus;
  /**
     * @minimum 1900
     * @maximum 2100
     */
  release_year?: number;
  second_title?: string;
  showing_date?: string;
  /**
     * @minLength 1
     * @maxLength 255
     */
  slug?: string;
  tag_ids?: string[];
  /**
     * @minLength 1
     * @maxLength 500
     */
  title: string;
  translation_status: RequestCreateMangaRequestTranslationStatus;
  translator_ids?: string[];
  type: RequestCreateMangaRequestType;
}
