/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface RequestAdminTopupRequest {
  amount: number;
  external_user_id?: number;
  reason: string;
  user_id?: string;
}
