/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type RequestBulkCreateNotificationsRequestPlatform = typeof RequestBulkCreateNotificationsRequestPlatform[keyof typeof RequestBulkCreateNotificationsRequestPlatform];


export const RequestBulkCreateNotificationsRequestPlatform = {
  telegram: 'telegram',
  all: 'all',
  system: 'system',
  email: 'email',
  push: 'push',
} as const;
