/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface RequestVerifyRequest {
  code: string;
  device_name?: string;
  device_token?: string;
  device_type?: string;
}
