/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type RequestCreateNovelRequestAgeRestriction = typeof RequestCreateNovelRequestAgeRestriction[keyof typeof RequestCreateNovelRequestAgeRestriction];


export const RequestCreateNovelRequestAgeRestriction = {
  all: 'all',
  '12+': '12+',
  '16+': '16+',
  '18+': '18+',
} as const;
