/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseTranslatorAccountResponse {
  account_id?: string;
  balance?: number;
  in_progress_drafts?: number;
  paid_chapters_count?: number;
  rate_per_chapter?: number;
  total_chapters?: number;
  total_earnings?: number;
  user_id?: string;
}
