/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseSubscriptionPlanResponse {
  created_at?: string;
  description?: string;
  duration_days?: number;
  is_active?: boolean;
  is_connected?: boolean;
  name?: string;
  plan_id?: string;
  price?: number;
  updated_at?: string;
}
