/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseScheduledChapterItemResponse } from './responseScheduledChapterItemResponse';
import type { ResponseScheduledMangaItemResponse } from './responseScheduledMangaItemResponse';

export interface ResponseScheduledResponse {
  chapters?: ResponseScheduledChapterItemResponse[];
  manga?: ResponseScheduledMangaItemResponse[];
}
