/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseFileResponse {
  file_key?: string;
  index?: number;
  upload_url?: string;
}
