/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseHomeCategoryResponse {
  content_types?: string[];
  created_at?: string;
  genre_ids?: string[];
  home_category_id?: string;
  is_active?: boolean;
  limit?: number;
  order_index?: number;
  sort_by?: string;
  time_period?: string;
  title?: string;
  updated_at?: string;
}
