/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseTranslatorTransactionResponse } from './responseTranslatorTransactionResponse';

export interface ResponseTranslatorTransactionListResponse {
  items?: ResponseTranslatorTransactionResponse[];
  next_cursor?: string;
}
