/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseChapterPaymentRateResponse {
  amount_per_chapter?: number;
  created_at?: string;
  created_by?: string;
  description?: string;
  is_active?: boolean;
  rate_id?: string;
}
