/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseReportUserResponse } from './responseReportUserResponse';

export interface ResponseReportResponse {
  chapter_id?: string;
  chapter_title?: string;
  comment_author?: string;
  comment_id?: string;
  comment_text?: string;
  created_at?: string;
  manga_id?: string;
  manga_title?: string;
  message?: string;
  report_id?: string;
  report_type?: string;
  status?: string;
  user?: ResponseReportUserResponse;
}
