/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseMangaResponse } from './responseMangaResponse';

export interface ResponseListMangaResponse {
  data?: ResponseMangaResponse[];
  limit?: number;
  offset?: number;
  page?: number;
  total?: number;
}
