/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseNotificationResponse } from './responseNotificationResponse';

export interface ResponseListNotificationsResponse {
  notifications?: ResponseNotificationResponse[];
  total_count?: string;
}
