/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseChapterNavInfo } from './responseChapterNavInfo';
import type { ResponseUploadedByUserInfo } from './responseUploadedByUserInfo';

export interface ResponseNovelChapterResponse {
  chapter_id?: string;
  chapter_number?: number;
  content?: string;
  created_at?: string;
  is_free?: boolean;
  is_liked?: boolean;
  is_read?: boolean;
  is_showed?: boolean;
  likes_count?: number;
  next?: ResponseChapterNavInfo;
  novel_id?: string;
  prev?: ResponseChapterNavInfo;
  release_date?: string;
  title?: string;
  total_chapters?: number;
  translator?: ResponseUploadedByUserInfo;
  updated_at?: string;
  views_count?: number;
}
