/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponsePresetAvatarResponse {
  created_at?: string;
  id?: string;
  image_link?: string;
  updated_at?: string;
}
