/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseGenreResponse {
  created_at?: string;
  description?: string;
  genre_id?: string;
  name?: string;
  updated_at?: string;
}
