/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseTransactionWithUserResponse } from './responseTransactionWithUserResponse';

export interface ResponseTransactionWithUserListResponse {
  items?: ResponseTransactionWithUserResponse[];
  next_cursor?: string;
}
