/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseChapterDraftListItemAction } from './responseChapterDraftListItemAction';
import type { ResponseChapterDraftListItemStatus } from './responseChapterDraftListItemStatus';
import type { ResponseUploadedByUserInfo } from './responseUploadedByUserInfo';

export interface ResponseChapterDraftListItem {
  action?: ResponseChapterDraftListItemAction;
  chapter_number?: number;
  created_at?: string;
  draft_id?: string;
  is_free?: boolean;
  is_novella?: boolean;
  manga_id?: string;
  pages_count?: number;
  reject_reason?: string;
  reviewed_at?: string;
  reviewed_by?: ResponseUploadedByUserInfo;
  status?: ResponseChapterDraftListItemStatus;
  target_chapter_id?: string;
  title?: string;
  uploaded_by?: ResponseUploadedByUserInfo;
}
