/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseUploadedByUserInfo } from './responseUploadedByUserInfo';

export interface ResponseContentDraftListItem {
  cover_image_url?: string;
  created_at?: string;
  created_manga_id?: string;
  draft_id?: string;
  message_to_moderator?: string;
  reject_reason?: string;
  requested_by?: ResponseUploadedByUserInfo;
  reviewed_at?: string;
  reviewed_by?: ResponseUploadedByUserInfo;
  slug?: string;
  status?: string;
  title?: string;
  type?: string;
}
