/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseTranslatorInfo {
  first_name?: string;
  manga_id?: string;
  picture_link?: string;
  translator_id?: string;
}
