/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseAccessibleContentItem {
  created_at?: string;
  image_url?: string;
  is_showed?: boolean;
  manga_id?: string;
  release_status?: string;
  slug?: string;
  title?: string;
  translation_status?: string;
  type?: string;
}
