/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type ResponseChapterDraftListItemAction = typeof ResponseChapterDraftListItemAction[keyof typeof ResponseChapterDraftListItemAction];


export const ResponseChapterDraftListItemAction = {
  create: 'create',
  update: 'update',
} as const;
