/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type ResponseChapterDraftResponseAction = typeof ResponseChapterDraftResponseAction[keyof typeof ResponseChapterDraftResponseAction];


export const ResponseChapterDraftResponseAction = {
  create: 'create',
  update: 'update',
} as const;
