/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseChapterDraftPage } from './responseChapterDraftPage';
import type { ResponseChapterDraftResponseAction } from './responseChapterDraftResponseAction';
import type { ResponseChapterDraftResponseStatus } from './responseChapterDraftResponseStatus';
import type { ResponseDraftMark } from './responseDraftMark';
import type { ResponseUploadedByUserInfo } from './responseUploadedByUserInfo';

export interface ResponseChapterDraftResponse {
  action?: ResponseChapterDraftResponseAction;
  chapter_number?: number;
  content?: string;
  created_at?: string;
  draft_id?: string;
  is_free?: boolean;
  is_showed?: boolean;
  manga_id?: string;
  marks?: ResponseDraftMark[];
  pages?: ResponseChapterDraftPage[];
  reject_reason?: string;
  release_date?: string;
  reviewed_at?: string;
  reviewed_by?: ResponseUploadedByUserInfo;
  showing_date?: string;
  status?: ResponseChapterDraftResponseStatus;
  target_chapter_id?: string;
  title?: string;
  tool_project_id?: string;
  updated_at?: string;
  uploaded_by?: ResponseUploadedByUserInfo;
}
