/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseReportUserResponse {
  display_name?: string;
  picture_link?: string;
  user_id?: string;
}
