/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseUploadedByUserInfo } from './responseUploadedByUserInfo';

export interface ResponseUploadChapterDraftResponse {
  chapter_number?: number;
  draft_id?: string;
  manga_id?: string;
  pages_count?: number;
  uploaded_by?: ResponseUploadedByUserInfo;
}
