/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseTransactionResponse } from './responseTransactionResponse';

export interface ResponseTransactionListResponse {
  items?: ResponseTransactionResponse[];
  next_cursor?: string;
}
