/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseHomeCategoryResponse } from './responseHomeCategoryResponse';

export interface ResponseHomeCategoryListResponse {
  data?: ResponseHomeCategoryResponse[];
  limit?: number;
  page?: number;
  total?: number;
}
