/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseCategoryInfo } from './responseCategoryInfo';
import type { ResponseChapterResponseSimple } from './responseChapterResponseSimple';
import type { ResponseGenreInfo } from './responseGenreInfo';
import type { ResponseTranslatorInfo } from './responseTranslatorInfo';

export interface ResponseNovelResponse {
  age_restriction?: string;
  author?: string;
  average_rating?: number;
  bookmarked_count?: number;
  categories?: ResponseCategoryInfo[];
  chapters?: ResponseChapterResponseSimple[];
  chapters_count?: number;
  created_at?: string;
  description?: string;
  genres?: ResponseGenreInfo[];
  image_url?: string;
  is_bookmarked?: boolean;
  is_comment_enabled?: boolean;
  likes_count?: number;
  novel_id?: string;
  real_link?: string;
  release_status?: string;
  release_year?: number;
  second_title?: string;
  slug?: string;
  title?: string;
  translation_status?: string;
  translators?: ResponseTranslatorInfo[];
  updated_at?: string;
  views_count?: number;
}
