/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseChapterNavInfo } from './responseChapterNavInfo';
import type { ResponseChapterTranslatorInfo } from './responseChapterTranslatorInfo';
import type { ResponsePage } from './responsePage';

export interface ResponseChapterResponse {
  chapter_id?: string;
  chapter_number?: number;
  created_at?: string;
  delete_cause?: string;
  deleted_at?: string;
  is_free?: boolean;
  is_liked?: boolean;
  is_read?: boolean;
  likes_count?: number;
  manga_id?: string;
  next?: ResponseChapterNavInfo;
  pages?: ResponsePage[];
  prev?: ResponseChapterNavInfo;
  release_date?: string;
  title?: string;
  total_chapters?: number;
  translator?: ResponseChapterTranslatorInfo;
  updated_at?: string;
  views_count?: number;
}
