/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseNotificationPreferencesResponse {
  content_enabled?: boolean;
  email_enabled?: boolean;
  push_enabled?: boolean;
  security_enabled?: boolean;
  system_enabled?: boolean;
  telegram_enabled?: boolean;
  user_enabled?: boolean;
  user_id?: string;
}
