/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseToolLinkBadge {
  linked_at?: string;
  tool_user_id?: string;
  tool_username?: string;
}
