/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseTagResponse } from './responseTagResponse';

export interface ResponseTagListResponse {
  data?: ResponseTagResponse[];
  limit?: number;
  page?: number;
  total?: number;
}
