/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseFileRequest } from './responseFileRequest';

export interface ResponseBulkUploadRequest {
  files?: ResponseFileRequest[];
}
