/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseNovelChapterSimple {
  chapter_id?: string;
  chapter_number?: number;
  created_at?: string;
  is_free?: boolean;
  is_liked?: boolean;
  is_read?: boolean;
  likes_count?: number;
  novel_id?: string;
  release_date?: string;
  title?: string;
  views_count?: number;
}
