/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseDraftMarkBBox } from './responseDraftMarkBBox';

export interface ResponseDraftMark {
  bbox?: ResponseDraftMarkBBox;
  comment?: string;
  id?: string;
  page_index?: number;
}
