/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponsePage {
  chapter_id?: string;
  height?: number;
  image_url?: string;
  page_id?: string;
  page_number?: number;
  width?: number;
}
