/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseScheduledMangaItemResponse {
  manga_id?: string;
  showing_date?: string;
  slug?: string;
  title?: string;
}
