/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseCommentResponse } from './responseCommentResponse';
import type { ResponsePublicUserResponse } from './responsePublicUserResponse';
import type { ResponseRepliesToUserResponse } from './responseRepliesToUserResponse';

export interface ResponseCommentWithUserResponse {
  comment?: ResponseCommentResponse;
  is_liked?: boolean;
  likes_count?: number;
  replies?: ResponseCommentWithUserResponse[];
  replies_count?: number;
  replies_to_user?: ResponseRepliesToUserResponse;
  user?: ResponsePublicUserResponse;
}
