/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseNovelResponse } from './responseNovelResponse';

export interface ResponseListNovelResponse {
  data?: ResponseNovelResponse[];
  limit?: number;
  offset?: number;
  total?: number;
}
