/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { EntityBookmarkResponse } from './entityBookmarkResponse';

export interface ResponseListBookmarksResponse {
  bookmarks?: EntityBookmarkResponse[];
  limit?: number;
  offset?: number;
  total?: number;
}
