/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseCommentWithUserResponse } from './responseCommentWithUserResponse';

export interface ResponseCommentListResponse {
  comments?: ResponseCommentWithUserResponse[];
  total?: number;
}
