/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseChapterNavInfo {
  chapter_id?: string;
  chapter_number?: number;
  is_free?: boolean;
  title?: string;
}
