/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseScheduledChapterItemResponse {
  chapter_id?: string;
  chapter_number?: number;
  manga_id?: string;
  manga_slug?: string;
  manga_title?: string;
  showing_date?: string;
  title?: string;
}
