/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type ResponseMangaResponseTranslationStatus = typeof ResponseMangaResponseTranslationStatus[keyof typeof ResponseMangaResponseTranslationStatus];


export const ResponseMangaResponseTranslationStatus = {
  finished: 'finished',
  freezed: 'freezed',
  'no-translator': 'no-translator',
  continue: 'continue',
} as const;
