/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseCreateNovelResponse {
  message?: string;
  novel_id?: string;
  slug?: string;
}
