/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type ResponseMangaResponseReleaseStatus = typeof ResponseMangaResponseReleaseStatus[keyof typeof ResponseMangaResponseReleaseStatus];


export const ResponseMangaResponseReleaseStatus = {
  finished: 'finished',
  freezed: 'freezed',
  'no-translator': 'no-translator',
  continue: 'continue',
  ongoing: 'ongoing',
} as const;
