/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseContentDraftListItem } from './responseContentDraftListItem';

export interface ResponseListContentDraftsResponse {
  drafts?: ResponseContentDraftListItem[];
  limit?: number;
  offset?: number;
  total?: number;
}
