/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseAccessibleContentItem } from './responseAccessibleContentItem';

export interface ResponseListAccessibleContentsResponse {
  data?: ResponseAccessibleContentItem[];
  limit?: number;
  offset?: number;
  total?: number;
}
