/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseChapterResponse } from './responseChapterResponse';

export interface ResponseListChaptersResponse {
  chapters?: ResponseChapterResponse[];
  limit?: number;
  offset?: number;
  total?: number;
}
