/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseTagResponse {
  created_at?: string;
  name?: string;
  tag_id?: string;
  updated_at?: string;
}
