/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseMangaSimple } from './responseMangaSimple';

export interface ResponseListAllMangaResponse {
  mangas?: ResponseMangaSimple[];
  total?: number;
}
