/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type ResponseNotificationResponseStatus = typeof ResponseNotificationResponseStatus[keyof typeof ResponseNotificationResponseStatus];


export const ResponseNotificationResponseStatus = {
  unread: 'unread',
  read: 'read',
} as const;
