/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseTransactionWithUserResponse {
  amount?: number;
  chapter_id?: string;
  created_at?: string;
  first_name?: string;
  last_name?: string;
  manga_id?: string;
  payment_method?: string;
  plan_id?: string;
  reason?: string;
  status?: string;
  transaction_id?: string;
  transaction_type?: string;
  user_id?: string;
  username?: string;
}
