/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseCategoryResponse } from './responseCategoryResponse';

export interface ResponseCategoryListResponse {
  data?: ResponseCategoryResponse[];
  total?: number;
}
