/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseDraftMarkBBox {
  h?: number;
  w?: number;
  x?: number;
  y?: number;
}
