/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseUserAboutResponse {
  bookmarks_count?: number;
  chapters_read_count?: number;
  comments_count?: number;
  external_user_id?: number;
  name?: string;
  picture_link?: string;
  ratings_count?: number;
  role?: string;
  user_id?: string;
  views_count?: number;
}
