/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseReadingProgressDetailResponse {
  chapter_id?: string;
  chapter_number?: number;
  chapter_title?: string;
  current_chapter?: number;
  current_chapter_rank?: number;
  is_bookmarked?: boolean;
  last_page_id?: string;
  last_page_number?: number;
  last_read_at?: string;
  manga_id?: string;
  manga_image_url?: string;
  manga_slug?: string;
  manga_title?: string;
  progress_id?: string;
  progress_percentage?: number;
  total_chapters?: number;
  total_chapters_in_manga?: number;
  total_pages_in_chapter?: number;
}
