/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseNotificationResponsePlatform } from './responseNotificationResponsePlatform';
import type { ResponseNotificationResponseStatus } from './responseNotificationResponseStatus';
import type { ResponseNotificationResponseType } from './responseNotificationResponseType';

export interface ResponseNotificationResponse {
  button_text?: string;
  button_url?: string;
  chapter_id?: string;
  content?: string;
  created_at?: string;
  id?: string;
  is_bookmarked?: boolean;
  manga_id?: string;
  photo_url?: string;
  platform?: ResponseNotificationResponsePlatform;
  read_at?: string;
  related_id?: string;
  status?: ResponseNotificationResponseStatus;
  title?: string;
  type?: ResponseNotificationResponseType;
  user_id?: string;
  webapp_button_text?: string;
  webapp_button_url?: string;
}
