/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type ResponseChapterDraftListItemStatus = typeof ResponseChapterDraftListItemStatus[keyof typeof ResponseChapterDraftListItemStatus];


export const ResponseChapterDraftListItemStatus = {
  draft: 'draft',
  pending_review: 'pending_review',
  approved: 'approved',
  rejected: 'rejected',
} as const;
