/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseTransactionDetailResponse {
  amount?: number;
  cancelled_at?: string;
  chapter_id?: string;
  created_at?: string;
  description?: string;
  manga_id?: string;
  payment_method?: string;
  perform_time?: string;
  plan_id?: string;
  provider_transaction_id?: string;
  purchase_type?: string;
  reason?: string;
  status?: string;
  transaction_id?: string;
  transaction_type?: string;
  user_id?: string;
}
