/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseToolLinkBadge } from './responseToolLinkBadge';
import type { ResponseUserResponseAdminScope } from './responseUserResponseAdminScope';

export interface ResponseUserResponse {
  admin_scope?: ResponseUserResponseAdminScope;
  balance?: number;
  banned?: boolean;
  chat_id?: number;
  created_at?: string;
  external_user_id?: number;
  first_name?: string;
  id?: string;
  last_name?: string;
  phone_number?: string;
  picture_link?: string;
  role?: string;
  tool_link?: ResponseToolLinkBadge;
  updated_at?: string;
  username?: string;
  warning?: number;
}
