/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponsePresetAvatarResponse } from './responsePresetAvatarResponse';

export interface ResponsePresetAvatarListResponse {
  data?: ResponsePresetAvatarResponse[];
  limit?: number;
  page?: number;
  total?: number;
}
