/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseCreateMangaResponse {
  manga_id?: string;
  message?: string;
  slug?: string;
}
