/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseFileResponse } from './responseFileResponse';

export interface ResponseBulkUploadResponse {
  items?: ResponseFileResponse[];
}
