/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseSubscriptionStatusResponse {
  expiry_date?: string;
  has_active_subscription?: boolean;
  plan_id?: string;
  plan_name?: string;
}
