/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseChapterTranslatorInfo {
  first_name?: string;
  id?: string;
  last_name?: string;
  picture_link?: string;
  username?: string;
}
