/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseCreateBookmarkResponse {
  bookmark_id?: string;
  manga_id?: string;
  message?: string;
}
