/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseChapterDraftListItem } from './responseChapterDraftListItem';

export interface ResponseListChapterDraftsResponse {
  drafts?: ResponseChapterDraftListItem[];
  limit?: number;
  offset?: number;
  total?: number;
}
