/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseBannerResponse } from './responseBannerResponse';

export interface ResponseBannerListResponse {
  data?: ResponseBannerResponse[];
  limit?: number;
  page?: number;
  total?: number;
}
