/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseTranslatorTransactionWithUserResponse } from './responseTranslatorTransactionWithUserResponse';

export interface ResponseTranslatorTransactionWithUserListResponse {
  items?: ResponseTranslatorTransactionWithUserResponse[];
  next_cursor?: string;
}
