/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseMangaResponse } from './responseMangaResponse';

export interface ResponseHomePageBlockResponse {
  /** same key as GET /manga (getall) for consistency */
  data?: ResponseMangaResponse[];
  home_category_id?: string;
  title?: string;
}
