/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseCommentResponse {
  chapter_id?: string;
  comment_id?: string;
  created_at?: string;
  is_deleted?: boolean;
  is_liked?: boolean;
  is_own_comment?: boolean;
  is_pinned?: boolean;
  likes_count?: number;
  manga_id?: string;
  parent_comment_id?: string;
  pinned_at?: string;
  replies?: ResponseCommentResponse[];
  replies_count?: number;
  replies_to_user_id?: string;
  text?: string;
  updated_at?: string;
  user_id?: string;
}
