/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type ResponseContentDraftResponseStatus = typeof ResponseContentDraftResponseStatus[keyof typeof ResponseContentDraftResponseStatus];


export const ResponseContentDraftResponseStatus = {
  pending_review: 'pending_review',
  approved: 'approved',
  rejected: 'rejected',
} as const;
