/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseCategoryInfo } from './responseCategoryInfo';
import type { ResponseChapterResponseSimple } from './responseChapterResponseSimple';
import type { ResponseGenreInfo } from './responseGenreInfo';
import type { ResponseMangaResponseAgeRestriction } from './responseMangaResponseAgeRestriction';
import type { ResponseMangaResponseReleaseStatus } from './responseMangaResponseReleaseStatus';
import type { ResponseMangaResponseTranslationStatus } from './responseMangaResponseTranslationStatus';
import type { ResponseMangaResponseType } from './responseMangaResponseType';
import type { ResponseTranslatorInfo } from './responseTranslatorInfo';

export interface ResponseMangaResponse {
  age_restriction?: ResponseMangaResponseAgeRestriction;
  author?: string;
  average_rating?: number;
  bookmarked_count?: number;
  categories?: ResponseCategoryInfo[];
  chapters?: ResponseChapterResponseSimple[];
  chapters_count?: number;
  created_at?: string;
  description?: string;
  genres?: ResponseGenreInfo[];
  image_url?: string;
  is_bookmarked?: boolean;
  is_showed?: boolean;
  likes_count?: number;
  manga_id?: string;
  real_link?: string;
  release_status?: ResponseMangaResponseReleaseStatus;
  release_year?: number;
  second_title?: string;
  showing_date?: string;
  slug?: string;
  title?: string;
  translation_status?: ResponseMangaResponseTranslationStatus;
  translators?: ResponseTranslatorInfo[];
  type?: ResponseMangaResponseType;
  updated_at?: string;
  views_count?: number;
}
