/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { EntityReadingHistoryItem } from './entityReadingHistoryItem';

export interface ResponseReadingHistoryResponse {
  history?: EntityReadingHistoryItem[];
  limit?: number;
  offset?: number;
  total?: number;
}
