/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseTranslatorTransactionResponse {
  amount?: number;
  chapter_id?: string;
  chapters_count?: number;
  created_at?: string;
  description?: string;
  draft_id?: string;
  rate_per_chapter?: number;
  status?: string;
  transaction_id?: string;
  transaction_type?: string;
  translator_id?: string;
}
