/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseNovelChapterSimple } from './responseNovelChapterSimple';

export interface ResponseListNovelChaptersResponse {
  chapters?: ResponseNovelChapterSimple[];
  total?: number;
}
