/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type ResponseNotificationResponsePlatform = typeof ResponseNotificationResponsePlatform[keyof typeof ResponseNotificationResponsePlatform];


export const ResponseNotificationResponsePlatform = {
  all: 'all',
  web: 'web',
  android: 'android',
  ios: 'ios',
} as const;
