/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseDonationStatResponse {
  chapter_id?: string;
  chapter_number?: string;
  chapter_title?: string;
  donation_count?: number;
  manga_id?: string;
  manga_slug?: string;
  manga_title?: string;
  total_donated?: number;
}
