/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export type ResponseUserResponseAdminScope = typeof ResponseUserResponseAdminScope[keyof typeof ResponseUserResponseAdminScope];


export const ResponseUserResponseAdminScope = {
  all: 'all',
  manga: 'manga',
  novel: 'novel',
} as const;
