/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { ResponseContentDraftResponseStatus } from './responseContentDraftResponseStatus';
import type { ResponseContentDraftResponseType } from './responseContentDraftResponseType';
import type { ResponseUploadedByUserInfo } from './responseUploadedByUserInfo';

export interface ResponseContentDraftResponse {
  age_restriction?: string;
  author?: string;
  category_ids?: string[];
  cover_image_url?: string;
  created_at?: string;
  created_manga_id?: string;
  description?: string;
  draft_id?: string;
  genre_ids?: string[];
  is_comment_enabled?: boolean;
  message_to_moderator?: string;
  real_link?: string;
  reject_reason?: string;
  release_status?: string;
  release_year?: number;
  requested_by?: ResponseUploadedByUserInfo;
  reviewed_at?: string;
  reviewed_by?: ResponseUploadedByUserInfo;
  second_title?: string;
  showing_date?: string;
  slug?: string;
  status?: ResponseContentDraftResponseStatus;
  tag_ids?: string[];
  title?: string;
  translation_status?: string;
  translator_ids?: string[];
  type?: ResponseContentDraftResponseType;
  updated_at?: string;
}
