/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface ResponseReadingProgressResponse {
  chapter_id?: string;
  chapter_title?: string;
  created_at?: string;
  is_bookmarked?: boolean;
  last_page_id?: string;
  last_page_number?: number;
  last_read_at?: string;
  manga_id?: string;
  manga_title?: string;
  progress_id?: string;
  progress_percentage?: number;
  updated_at?: string;
  user_id?: string;
}
