/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface V2ActivityHistoryResponse {
  chapters_count?: number;
  manga_count?: number;
  month?: string;
  users_count?: number;
}
