/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { EntityAdminLogItem } from './entityAdminLogItem';

export interface V2AdminLogsResponse {
  items?: EntityAdminLogItem[];
  next_cursor_created_at?: string;
  next_cursor_id?: string;
}
