/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface V2CreateChapterPaymentRateBody {
  amount_per_chapter: number;
  description?: string;
}
