/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface V2TopTranslatorResponse {
  chapters_count?: number;
  first_name?: string;
  last_name?: string;
  manga_count?: number;
  picture_link?: string;
  user_id?: string;
  username?: string;
}
