/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface V2TopTagResponse {
  manga_count?: number;
  name?: string;
  tag_id?: string;
  total_views?: number;
}
