/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */
import type { V2TranslatorChapterStatResponse } from './v2TranslatorChapterStatResponse';

export interface V2TranslatorChapterStatsResponse {
  chapters?: V2TranslatorChapterStatResponse[];
  total?: number;
}
