/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface V2TranslatorChapterStatResponse {
  chapter_id?: string;
  chapter_number?: string;
  donation_count?: number;
  likes_count?: number;
  manga_id?: string;
  manga_title?: string;
  manga_type?: string;
  title?: string;
  total_donated?: number;
  views_count?: number;
}
