/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface V2TranslatorContentStatsResponse {
  chapters_count?: number;
  donation_count?: number;
  manga_id?: string;
  title?: string;
  total_donated?: number;
  total_likes?: number;
  total_views?: number;
  type?: string;
}
