/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mano API
 * Mano API
 * OpenAPI spec version: 2.0
 */

export interface V2TranslatorContentResponse {
  average_rating?: number;
  chapters_count?: number;
  image_url?: string;
  likes_count?: number;
  manga_id?: string;
  slug?: string;
  title?: string;
  type?: string;
  views_count?: number;
}
